# Generated by Django 6.0.5 on 2026-05-24 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'MASCULINO'), ('F', 'FEMININO'), ('NA', 'NÃO INFORMAR')], max_length=20, null=True),
        ),
    ]
