# Generated by Django 6.0.5 on 2026-05-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_endereco_cliente_endereco_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregador',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entregador',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'MASCULINO'), ('F', 'FEMININO'), ('NA', 'NÃO INFORMAR')], max_length=20, null=True),
        ),
    ]
