# Generated by Django 6.0.5 on 2026-05-25 16:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_entregador_data_nascimento_entregador_sexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntregadorLocalizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('velocidade', models.FloatField(blank=True, null=True)),
                ('heading', models.FloatField(blank=True, null=True)),
                ('disponivel', models.BooleanField(default=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('entregador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='localizacao', to='core.entregador')),
            ],
        ),
        migrations.CreateModel(
            name='SessaoRastreamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online', models.BooleanField(default=False)),
                ('iniciado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('entregador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes_rastreamento', to='core.entregador')),
            ],
        ),
    ]
