# Generated by Django 6.0.5 on 2026-05-25 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_entregador_data_nascimento_entregador_sexo'),
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoLocalizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('velocidade', models.FloatField(blank=True, null=True)),
                ('heading', models.FloatField(blank=True, null=True)),
                ('registrado_em', models.DateTimeField(auto_now_add=True)),
                ('entregador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_localizacao', to='core.entregador')),
            ],
            options={
                'ordering': ['registrado_em'],
            },
        ),
    ]
