# Generated by Django 6.0.5 on 2026-05-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_historicolocalizacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregadorlocalizacao',
            name='latitude',
            field=models.DecimalField(decimal_places=10, max_digits=15),
        ),
        migrations.AlterField(
            model_name='entregadorlocalizacao',
            name='longitude',
            field=models.DecimalField(decimal_places=10, max_digits=15),
        ),
        migrations.AlterField(
            model_name='historicolocalizacao',
            name='latitude',
            field=models.DecimalField(decimal_places=10, max_digits=15),
        ),
        migrations.AlterField(
            model_name='historicolocalizacao',
            name='longitude',
            field=models.DecimalField(decimal_places=10, max_digits=15),
        ),
    ]
